name = "glen_node"
version = "0.0.2"

description = "NodeJS adapter for the Glen web framework"
licences = ["Apache-2.0"]
repository = { type = "github", user = "Enderchief", repo = "glen_node" }

target = "javascript"

[dependencies]
glen = ">= 2.2.0 and < 3.0.0"
gleam_javascript = ">= 0.8.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
